{% set name = "nr.config" %}
{% set version = "1.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "6f9986e507a247996ff0a78b760f483f5222e8e89d2507295af15005d0906c18"

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - nr.types >=2.1.0
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - nr

about:
  home: "https://github.com/NiklasRosenstein/python-nr.config"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "This packages provides a class-oriented API for parsing YAMl/JSON configs."

extra:
  recipe-maintainers:
    - NiklasRosenstein
